server:
  port: 8081
  servlet:
    context-path: /gst-project
# 支持jsp
spring:
  resources:
    chain:
      strategy:
        content:
          paths: /**
          enabled: true
 # http:
   # encoding:
     # charset: UTF-8
     # enabled: true
     # force: true
    # static-locations: classpath:/static/**
  #mvc:
   # static-path-pattern: /upload/**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://ifashioncloud.mysql.rds.aliyuncs.com:3306/gst_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: gst_user
    password: 'gst#123456'
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # config,stat,wall,log4j
    filters: config,stat,wall
    #初始化连接
    initialSize: 5
    #最小空闲连接
    minIdle: 5
    #最大连接数量
    maxActive: 2000
    #超时等待时间以毫秒为单位 60000毫秒/1000等于60秒
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
      file-size-threshold: 0
      #location:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 10.7.121.45:9300
      repositories:
        enabled: true
#  redis:
#    database: 0 #redis数据库索引(默认为0)
#    host: 10.7.121.45  #redis服务器地址
#    port: 6379
#    password: cappGst2020 #redis连接密码
#    jedis:
#      pool:
#        max-active: 100 #最大连接数
#        max-idle: 10 #最大空闲连接
#        min-idle: 1 #最小空闲连接
#        max-wait: 100000 #最大阻塞等待时间(负数表示没有限制)


#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  config-location: classpath:mybatis-config.xml
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: false
  params: count=countSql
logging:
  level:
    com.ylzs.dao: error

mybatis-plus:
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.ylzs.entity
  field-strategy: 1
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto